### ISSUE TITLE
Mine "Power tools" (latest from git) looks totally different (lack of frequency selection)

### ISSUE THREAD

**Issue by isopix** [NGnius/PowerTools#1]
Mine "Power tools" (latest from git) looks totally different.
I got only "Online CPUs selection" and "CPU Boost Switch", without any frequency setting....

do I need to run it in some special way as 'root'?

**Comment by isopix** [comment]
SteamDeck's 'git' doesn't support 'git up' command, so scripts were outdated....

**Comment by NGnius** [comment]
I've been hearing from people not realising that the latest version isn't the same as the latest release ever since I released v0.1.1 onto the plugins list. I'm going to try to do development work in a separate branch from now on to avoid confusion.

**Comment by isopix** [comment]
My problem was not related, but because installing from interface doesn''t worked, I git cloned all plugins, and made scripts that called 'git up' from loop (but SteamDeck doesn't support it)

So I wrote another one:

#!/bin/sh
chmod -R 750 ~/homebrew 
cd ~/homebrew/plugins
# https://plugins.deckbrew.xyz/
for i in SteamDeckHomebrew/Mopidy-Controller SteamDeckHomebrew/ExtraSettingsPlugin SpyrexDE/SDH-BigPictureMode SpyrexDE/SDH-Calculator NegativeI0N/SDH-ClassicTheme SteamDeckHomebrew/ExtraSettingsPlugin NGnius/PowerTools suchmememanyskill/SDH-CssLoader; do
        echo "refetching: $i"
        rm -rf "`basename $i`"
        git clone --recursive "https://github.com/$i"
done
