### ISSUE TITLE
Beta Support

### ISSUE THREAD

**Issue by NGnius** [NGnius/PowerTools#10]
**Describe what you'd like to be able to do**
SteamOS beta has some software differences from SteamOS stable which make it harder to support

**Describe alternatives you've considered**
Only using SteamOS stable. Apparently some people enjoy being on the bleeding edge

**Additional context**
How hard is it to switch between beta and stable versions? Would it be better to buy an extra SSD or SD card to accomplish this?

**Comment by milroneth** [comment]
> How hard is it to switch between beta and stable versions?
It is supposedly very easy, but has too big a chance to break things currently, so I don't think it's worth it, especially not just to test preemptively, unless something is reported to be broken.

**Comment by NGnius** [comment]
Yeah that's why I was thinking using another storage drive would be a reasonably good idea. Best option would be to buy another Steam Deck, but I'm not willing to pay $500+ just to be able to better support it. Similarly I can't really justify spending the money to buy a SSD or SD just for this project.

Anyway, not a big deal. I really just started this issue to keep track of how good/bad SteamOS beta is.

**Comment by NGnius** [comment]
I haven't encountered interop issues between beta and stable versions of SteamOS in a while, so closing as stale and unplanned. My support policy has not changed, I'm just cleaning up issues.
