### ISSUE TITLE
Minimum CPU frequency can't be set lower than 1400MHz.

### ISSUE THREAD

**Issue by k6storama** [NGnius/PowerTools#101]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

I'd expect to set minimum CPU frequency below 1400MHz.

### Actual Behaviour

Well, like in the title - the minimum CPU frequency can't be set below 1400MHz.
It can be set lower with the slider, though it has no actual effect; the minimum CPU clock speed & the value inside the game profile config is still at 1400.
The maximum frequency can be set lower than 1400MHz, making the minimum frequency higher than the maximum, and locking the actual CPU frequency at maximum frequency value as result.
This happens with every game I've tested, as well as in Steam Deck main menu ("Main" profile).

### Steps To Reproduce

1. Start the game
2. Open PowerTools settings
4. Enable CPU Frequency Limits
5. Set the minimum CPU frequency below 1400MHz
6. Enable Persistent Profile
7. Check the CPU frequencies with e.g. mangohud, restart the game to see the minimum CPU frequency slider at 1400MHz or check the game profile config (~/.config/powertools/GameID.json)

### Anything else?

Before the game restart:
![7_20230511194952_1](https://github.com/NGnius/PowerTools/assets/78875925/27d17a1e-339a-4c51-887c-96ee5915d022)
After restart:
![7_20230511195028_1](https://github.com/NGnius/PowerTools/assets/78875925/fe55ad82-0cc9-4e7c-9ebe-2e8ad2c3a15e)
Log file:
[powertools.log - Pastebin](https://pastebin.com/FVzAQWNL) 

### Version

1.3.1 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Stable)

**Comment by NGnius** [comment]
This is intended behavior, since the kernel does not allow minimum values lower than 1400MHz. It's also the reason for this slightly strange comment.

https://github.com/NGnius/PowerTools/blob/main/backend/src/settings/steam_deck/cpu.rs#L431
