### ISSUE TITLE
Issue with CPU and GPU Frequency Readings

### ISSUE THREAD

**Issue by patofet** [NGnius/PowerTools#108]
### Please confirm

- [X] I have searched existing issues and found no duplicate
- [X] I will fill this out to the best of my ability

### Extra details

- [ ] I am using a custom `pt_oc.json` file
- [ ] I am using a custom `limits_cache.json` file
- [ ] I have submitted a log through the PowerTools UI

### Expected Behaviour

PowerTools should accurately display the CPU and GPU frequencies, reflecting the changes made in the modified BIOS settings.

### Actual Behaviour

PowerTools displays the default CPU and GPU frequencies instead of the modified values set in the BIOS. This leads to inaccurate reporting of the actual frequencies.

### Steps To Reproduce

Install SteamOS version 3.5 (20230522.1000)
Modify the BIOS settings to change CPU and GPU frequencies.
Launch PowerTools on SteamOS.
Observe the reported CPU and GPU frequencies in PowerTools.

### Version

v1.3.1-2-rls

### Platform

SteamDeck

### OS

SteamOS 3 (Main)

**Comment by NGnius** [comment]
Please refer to [customization](https://github.com/NGnius/PowerTools/wiki/Customization) and the FAQ about [my stance on overclocking](https://github.com/NGnius/PowerTools/wiki/FAQ#can-this-overclock-my-steam-deck) and [using bleeding edge versions of SteamOS](https://github.com/NGnius/PowerTools/wiki/FAQ#does-this-work-on-steamos-beta-versions)
