### ISSUE TITLE
Adjust Current to show discharging and charging rates

### ISSUE THREAD

**Issue by VioletSnow08** [NGnius/PowerTools#110]
### Please confirm

- [x] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Describe what you'd like to be able to do

Currently, the Current shows the rate at which the device is discharging or charging. But in my opinion, it does not denote this clearly, or account for the discharge rate when charging and subtracting that.

### Describe alternatives you've considered

A possible way to fix this would be to denote whether the battery is discharging or charging by using "+" or "-" symbols. Another thing would be to account for battery consumption during charging and subtract that from the input current, to get the actual current of the battery.
For example, if the charger is 2500mA, the device is using 500mA, then the current is 2000mA. In cases like this, maybe display it as "Current: 2000mA (-500mA)". If the number is negative, it is discharging, otherwise, it is charging.

**Comment by NGnius** [comment]
This is a limitation of the sysfs API that PowerTools uses. The battery management system only reports a single current value which doesn't have a sign. I presume it's the absolute net current, but it's not like there's documentation I can check.

Closing since this isn't possible at the moment.
