### ISSUE TITLE
[3.5] - TDP path is wrong

### ISSUE THREAD

**Issue by Kiblyn11** [NGnius/PowerTools#115]
### Please confirm

- [X] I have searched existing issues and found no duplicate
- [X] I will fill this out to the best of my ability

### Extra details

- [X] I am using a custom `pt_oc.json` file
- [ ] I am using a custom `limits_cache.json` file
- [ ] I have submitted a log through the PowerTools UI

### Expected Behaviour

Changing TDP through slider should work

### Actual Behaviour

It does not work

### Steps To Reproduce

1. Change max TDP in bios
2. Launche game
3. Change TDP in powertools

### Anything else?

For some reason it is not exposed at `/sys/class/hwmon/hwmon4/power1_cap` but `/sys/class/hwmon/hwmon5/power1_cap` now... Same for power2.

### Version

Latest

### Platform

SteamDeck

### OS

SteamOS 3 (Main)

**Comment by NGnius** [comment]
This can probably be fixed by changes for #114 , so I'm going to close this in favour of that.

Please keep in mind that beta and dev versions of SteamOS are not officially supported by PowerTools, so bugs should be expected.
