### ISSUE TITLE
per-game profiles not working

### ISSUE THREAD

**Issue by SiriusVI87** [NGnius/PowerTools#15]
**Expected Behaviour**
Clicking on the per-game profile toggle should switch it on.

**Actual Behaviour**
clicking on the toggle to enable per-game profiles does nothing. The toggle won't slide to the right and won't turn blue.

Is anyone having the same experience?

**Comment by NGnius** [comment]
If PowerTools doesn't detect your game (thinks you're in the Menu), the toggle can't be enabled. 

Hopefully v0.7.0 improves it so it can detect games before you open PowerTools for the first time.
