### ISSUE TITLE
Plugin has to be reinstalled after every restart

### ISSUE THREAD

**Issue by TheRealRws** [NGnius/PowerTools#18]
**Expected Behaviour**
Plugin remains installed after restart.

**Actual Behaviour**
After every restart i have to reinstall the plugin.

**To Reproduce**
1. Install plugin
2. Restart steamdeck

I am running steamOS on beta.

**Comment by NGnius** [comment]
What version of PluginLoader and PowerTools are you using?

**Comment by TheRealRws** [comment]
Powertools 0.6.0 from the plugin "store" 

Pluginloader 1.3.1

**Comment by botatooo** [comment]
> Powertools 0.6.0 from the plugin "store"
> 
> Pluginloader 1.3.1

Can you show us your plugins folder?

**Comment by TheRealRws** [comment]
Dont have a log because after a restart they delete the logs

Plugins Folder]

![image](https://user-images.githubusercontent.com/92763718/177660334-27a44cb0-68a9-497e-9691-b81caa46bde1.png)

Power Tools Folder

![image](https://user-images.githubusercontent.com/92763718/177660280-fd77b679-8664-4045-94b8-aed0a93a67a7.png)

**Comment by TheRealRws** [comment]
[powertools.log](https://github.com/NGnius/PowerTools/files/9059224/powertools.log)

Found the log nvm

**Comment by NGnius** [comment]
It's probably a bad idea to have 2 instances of PowerTools running at the same time because they'll fight. That may be the problem.

**Comment by TheRealRws** [comment]
Will remove the older version and see how that goes. Guess it never deleted it when i updated at some point.

**Comment by TheRealRws** [comment]
Seems to have done it!

**Comment by NGnius** [comment]
Great! I'm going to close this, but feel free to re-open if it turns out that didn't actually fix it.
