### ISSUE TITLE
Using the plugin breaks the performance overlay (mangohud) until reboot

### ISSUE THREAD

**Issue by n00mkrad** [NGnius/PowerTools#2]
Not sure if this isn't just something on my end, but toggling SMT seems to break the performance overlay every time. It won't come back until I reboot the Deck.

**Comment by NGnius** [comment]
Yeah, I'm aware of this issue. It's one of the major reasons why the version which includes the SMT toggle isn't officially released yet

**Comment by NGnius** [comment]
Seems like a bug with MangoHud so I've reported it https://github.com/flightlessmango/MangoHud/issues/737
Now waiting for:
- [ ] fix for MangoHud
- [ ] update to SteamOS which includes the fix

**Comment by n00mkrad** [comment]
I see, thanks for the info

**Comment by NGnius** [comment]
SteamOS beta has apparently updated MangoHUD/App to a version with the bugfix. Still waiting for it to be in stable, but that mean it's coming.

Gain fixed performance overlay, lose fan controls; you win some you lose some.

**Comment by NGnius** [comment]
Looks like that update made it into stable as well https://steamcommunity.com/games/1675200/announcements/detail/3297210455204349336

**Comment by Haxorzz** [comment]
Hey, currently toggling SMT make it so every other core isn't used, or that's what mangohud says atleast (preview build)

**Comment by NGnius** [comment]
> Hey, currently toggling SMT make it so every other core isn't used, or that's what mangohud says atleast (preview build)

That's exactly what it's supposed to do

**Comment by Haxorzz** [comment]
I mean when I turn smt back ON it STILL does that
