### ISSUE TITLE
BT/Wifi/Rumble/Haptics control

### ISSUE THREAD

**Issue by adrian-smitto** [NGnius/PowerTools#26]
**Describe what you'd like to be able to do**
Currently these are available in quick settings but not per-game.
Would it be possible to add overrides to this? That way we can turn off this specific settings on a per-game basis while still having them enabled at the 'general' level in gaming mode
(specially wifi)

**Comment by NGnius** [comment]
Are there any advanced features that the BT/Wifi/Rumble/Haptics don't expose in the existing (vanilla) settings? I usually try not to mess with settings that Valve already has, because it's hard to keep them in sync and it doesn't offer any value to duplicate functionality.

**Comment by NGnius** [comment]
If someone implements this in way that enables extra performance or battery life, feel free to open a PR
