### ISSUE TITLE
Steam Client crashes randomly when opening UI elements

### ISSUE THREAD

**Issue by NGnius** [NGnius/PowerTools#29]
I have at least similar problems although I'm not sure it's exactly the same. Having PowerTools installed seems to cause crashes not only with the quick access menu but other overflowing Steam elements as well. These crashes seem to happen at least sometimes when a Steam Input radial menu is shown.

Also some Resetera user reported similar problems [here](https://www.resetera.com/threads/steam-deck-ot2-no-really-it%E2%80%99s-a-pc-2.620292/post-92502301) .

Can I provide some logs that might help investigate this? I'm on the latest stable SteamOS and have the latest Decky Loader (Prerelease v2.0.5-pre20) with the 0.7.0 PowerTools.

Edit: Reading the above comments more thoroughly, I'm not sure if they have actual crashes or just freezes. In my case, Steam actually restarts from "Verifying installation" so it's not just a freeze.

_Originally posted by @theCroh in https://github.com/NGnius/PowerTools/issues/13#issuecomment-1236200532_

**Comment by theCroh** [comment]
Does this sound like something that the upcoming backend rework may affect?

**Comment by NGnius** [comment]
I doubt it. I mentioned it to some of the Decky devs and they said it could even be an issue with SteamOS itself, since they've seen cases where it happens without Decky and PowerTools installed. So it could be unfixable on my end, idk

**Comment by theCroh** [comment]
I'm a bit worried that it's something hardware-related since it seems to affect only a handful of people. I asked around in the Resetera Steam Deck thread and I can find only one other person that's affected. For me, just uninstalling PowerTools _seems_ to "fix" this problem, though.

**Comment by NGnius** [comment]
Software-related issues can also only affect a handful of people. Right now I don't have enough information to come to a reasonable conclusion as to what is the cause. If someone finds a way to reproduce the crash reliably on any Deck, I'll look into it. Without a way to reproduce it on my Deck, I can't fix it.
