### ISSUE TITLE
Any Way to set 2 cores with SMT? (4 threads) 

### ISSUE THREAD

**Issue by Neukom720** [NGnius/PowerTools#32]
First of all wanted to thank everyone who has worked on this so far! Great work! But was wondering if there was a way to set 2 cores active with SMT active thus having 4 total threads? Might be a sweet spot to keep boost clock speeds high like 3.4-3.5ghz while keeping power usage low. Also some games, especially older titles, really like that extra boost clock because they were written for 1 or 2 cores. Just something I wanted to try in some games! Thanks Again Guys and hope we can maybe add this feature!

**Comment by NGnius** [comment]
Do you mean having all cores active, but only 2 of 4 having SMT enabled? Because that would be 6 threads total.
If you mean having only 2 cores active, each with SMT enabled, just leave the SMT toggle on and move the threads slider down to 4.

**Comment by Neukom720** [comment]
Yes exactly! For some reason I wasn't thinking of it that way sorry, and you guys do amazing stuff! Can't wait to see where the steam deck goes! It's just gonna get better and better, so glad I got mine a few weeks ago, it was crazy it took that long seeing I put my reservation in less than 24 hours after reservations opened!

**Comment by restfuladi** [comment]
> Do you mean having all cores active, but only 2 of 4 having SMT enabled? Because that would be 6 threads total. If you mean having only 2 cores active, each with SMT enabled, just leave the SMT toggle on and move the threads slider down to 4.
> 
> Thanks for the love, always appreciated :)

There may be value in exposing a hybrid configuration, some games have a heavy main or render thread that benefits from a dedicated core but also maybe have several worker threads that may benefit from more than 2-3 logical CPUs.
