### ISSUE TITLE
v1.0.0 doesn't show in Decky Loader Plugin Store

### ISSUE THREAD

**Issue by theCroh** [NGnius/PowerTools#33]
I'm not sure if this is the right place to report this but version 1.0.0 doesn't show in the plugin store. The latest one that is shown is v0.7.0. See https://beta.deckbrew.xyz or the integrated store in the latest Decky Loader pre-release.

**Comment by NGnius** [comment]
That's because the store update is still pending.
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/64

**Comment by theCroh** [comment]
Okay. Sorry about the fuzz. I thought the updates appeared immediately.
