### ISSUE TITLE
PowerTools (1.0.0) no longer detects certain non-Steam games

### ISSUE THREAD

**Issue by ohMoka** [NGnius/PowerTools#34]
Hi there, been loving PowerTools 1.0.0 so far. A regression I've noticed however is that certain non-Steam games aren't detected by the new version of PowerTools, and thus I'm unable to make per-game profiles for these games. In example, PowerTools no longer detects anything added from EmuDeck. Launching anything that was added from EmuDeck will just have the "Default" profile applied.
Other non-Steam games made for PC work perfectly fine on the other hand, such as XIVLauncher or games added to Steam from Lutris.

**Comment by NGnius** [comment]
Nice catch, looks like I was using the wrong ID for non-Steam games. A new release will be out in a couple of minutes to fix this.

**Comment by ohMoka** [comment]
Yep that fixed it! Thanks for the quick fix and a great plugin :-)
