### ISSUE TITLE
PowerTools 1.0.1 refuses to install. 

### ISSUE THREAD

**Issue by CorpseSea** [NGnius/PowerTools#35]
Hello, any attempt at updating to the latest uninstalls the previous version (1.0.0) and then nothing. Instaling 1.0.0 will install it but i dont have my power tools saved each time i try to launch a game (Team Fortress 2, any emulators, etc.)

Anyone else experiencing this? Is there a way to manually install 1.01.

**Comment by Energizing** [comment]
same issue here, last update seems broken

**Comment by CorpseSea** [comment]
> 

Aw, well here's to hoping it can be resolved if anyone has a solution.

**Comment by CorpseSea** [comment]
> Same here, the plugin disappears from the list. Trying to install from the store nets the same result.

Yeah, asked a different friend; that makes 4. Hopefully the Dev can fix it, this plugin is a must have IMO.

**Comment by NGnius** [comment]
Looks like the store broke and so the latest version can't be downloaded. For now please use v1.0.0, unless you want to manually install from the [release](https://github.com/NGnius/PowerTools/releases/tag/v1.0.1) (it's a bit of a pain, would not recommend).

I'm working with the Decky dev team to get it fixed, but it's mostly out of my hands. Sorry about that.

**Comment by TrainDoctor** [comment]
> Looks like the store broke and so the latest version can't be downloaded. For now please use v1.0.0, unless you want to manually install from the [release](https://github.com/NGnius/PowerTools/releases/tag/v1.0.1) (it's a bit of a pain, would not recommend).
> 
> I'm working with the Decky dev team to get it fixed, but it's mostly out of my hands. Sorry about that.

Something is busted with the CI, we're doing our best to get it sorted ASAP.

**Comment by NGnius** [comment]
Throwing this in here to keep track of. This is a PR to hopefully force the CI to rebuild for Train. Hopefully that's all that's needed, but I think we're both going to bed so it won't be fixed until at least tomorrow.

https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/66

**Comment by CorpseSea** [comment]
1.0.2 worked for me, there is an issue with it not recognizing Team Fortress 2, yet recognizing emulators; should i create a new bug thread about it?

**Comment by NGnius** [comment]
2 for 1, sweet! Looks like the store issue is resolved, so I'm closing this. If that other issue comes back, please open a new issue and send me the files in ~/.config/powertools
