### ISSUE TITLE
Powertools 1.0.4 seems to be effecting RPCS3 performance

### ISSUE THREAD

**Issue by Patient6038** [NGnius/PowerTools#37]
**Expected Behaviour**
Powertools being able to use the cpu properly in rpcs3 without massive stuttering or inconsistency in performance

**Actual Behaviour**
When booting a game on RPCS3 with Powertools **installed**, the cpu performance will become extremely choppy https://streamable.com/iyo6nh 
I've isolated the issue to powertools effecting the performance by uninstalling it and then running a ps3 game. Any games run fine with powertools uninstalled. It is not a single game that is being effected, it's the entire library with this stuttering. For some weird reason, after uninstalling PowerTools, the performance tab still shows 7 or 8 cores being used despite powertools being completely removed. The temporary solution is to uninstall PowerTools. Sometimes Reinstalling it from RPCS3 and then using it works. However, upon rebooting it later, the deck will go back to stuttering (I have tried to delete any profile tab that PowerTools keeps, but I cant find the location for it.) Lastly, I'm also getting crashing with PowerTools randomly after pressing ... sometimes: https://github.com/NGnius/PowerTools/issues/29

**To Reproduce**
1. Boot into RPCS3 with the PT settings for it (7 cores, 3100hz) 
2. Load into a game (doesnt matter which one, they're all effected)
3. Get massive stuttering https://streamable.com/iyo6nh 
4. temporarily fixed by uninstalling Powertools completely

**Screenshots, etc.**

https://streamable.com/iyo6nh 
Video of the problem. I did not record the performance with Powertools uninstalled, but it runs completely fine without Powertools installed.

Regarding the log file, launched RPCS3 from gaming mode, then went into desktop mode to retrieve the file. Tried running rpcs3 on desktop, then getting the log file and it still had the same results.
[powertools-rs.log](https://github.com/NGnius/PowerTools/files/9625124/powertools-rs.log)

**Comment by NGnius** [comment]
If you reset the settings to default (button at the bottom of PowerTools' menu), does the stuttering still occur?

Does anything change if you put the Deck to sleep (and then resume)?

For future reference, the files are stored in `~/.config/powertools/`.
The behaviour of threads not getting re-enabled when uninstall is unfortunately a limitation of the uninstall process. A restart should sort it though.

**Comment by Patient6038** [comment]
>If you reset the settings to default (button at the bottom of PowerTools' menu), does the stuttering still occur?
Actually that seems to have fixed the issue entirely. You can close this. If I ever run into any bugs, I'll make sure to try resetting it back to default before submitting.

**Comment by Patient6038** [comment]
>If you reset the settings to default (button at the bottom of PowerTools' menu), does the stuttering still occur?
Actually that seems to have fixed the issue entirely. If I ever run into any bugs, I'll make sure to try resetting it back to default before submitting.  

Thanks for helping. Closing this now.

**Comment by Patient6038** [comment]
Sadly I need to reopen this issue after updating Decky. Somehow, updating decky messed with my settings and now the stuttering is back. 

What I have tried:
1. Reset settings to default on PT
2. Completely uninstall powertools and remove the powertools config folder (restarted after)
3. reinstalled PT, completely restarted, then set the config for rpcs3 to my usual settings (7 cores 3100hz). 

All have resulted in stuttering. One thing I noticed was temperatures were getting much higher than previous configs.

**Comment by NGnius** [comment]
This is going to sound like something you've already done, but can you try reinstalling PowerTools? There was an issue with the store over the weekend which caused PowerTools to get removed, so I'm not sure if you may have been affected by that.

Otherwise, it sounds like a Decky loader issue. It may be worth re-running the install script for Decky to see if that changes anything. But I can't really do anything about Decky bugs, so you'd be better off asking for help on the [Decky Discord](https://discord.gg/ZU74G2NJzk).

**Comment by Patient6038** [comment]
> This is going to sound like something you've already done, but can you try reinstalling PowerTools? There was an issue with the store over the weekend which caused PowerTools to get removed, so I'm not sure if you may have been affected by that.
> 
> Otherwise, it sounds like a Decky loader issue. It may be worth re-running the install script for Decky to see if that changes anything. But I can't really do anything about Decky bugs, so you'd be better off asking for help on the [Decky Discord](https://discord.gg/ZU74G2NJzk).

Tried reinstalling, no avail, still the same issue. Thanks for all the help, I'll do that.
