### ISSUE TITLE
Number of available threads to choose

### ISSUE THREAD

**Issue by wekii** [NGnius/PowerTools#38]
**Expected Behaviour**
I expected to be always available 1 to 8 threads for choose.

**Actual Behaviour**
On steam gaming mode there is only 1 to 4 threads available for choose.
The same problem when I run dolphin game in gaming mode (EmuDeck).
When I run some PC game (e.g. Mafia II) there is all 8 options available.
At the begining there was always 8 options available and suddenly I see just 4 options.
I tried to reinstall PowerTools but problem is still present.

**To Reproduce**
1. Open PowerTools
2. There is 1 to 4 threads available to choose.

**Comment by NGnius** [comment]
Have you tried toggling SMT?

**Comment by wekii** [comment]
I'm sorry. You  were right. When I turn on SMT there is all 8 threads available. Thank you.
