### ISSUE TITLE
Please documents defaults, and when the plugin kicks in.

### ISSUE THREAD

**Issue by notimp** [NGnius/PowerTools#4]
Does the plugin auto engage (as in auto change any values), after a clean shutdown and reboot?

What is the default max frequency (governor)?

Why is CPU Boost enabled by default?

Please document stuff like that if possible. I'm trying to get a grip on when powertool engages, and what it takes to "get back to default".

Thank you.

**Comment by NGnius** [comment]
The plugin does not automatically set values -- PowerTools simply reads system settings and provides a nice UI to (manually) set them. Hence PowerTools doesn't do anything after a reboot (except, of course, reading the settings when PowerTools loads for the first time).

Max base frequency is 2.8GHz, as the frequency slider shows. With CPU boost enabled (the default), that'll go up to 3.5GHz per [the specs](https://www.steamdeck.com/en/tech).

Why wouldn't CPU Boost be enabled by default? You're leaving performance on the table if that's the case, so obviously Valve enabled CPU boost.

To reset PowerTools to default, either reboot your Steam Deck or remember the default state (in most cases, that's the auto/right-most position).
Note in v0.3.0 there are some GPU settings which can be set back to default, but this does not necessarily correspond to their previous value before changing them in PowerTools (to do that, you'll need to change the Steam Deck wattage setting in the vanilla SteamOS advanced power settings QAM)

**Comment by NGnius** [comment]
Created a FAQ which contains most of the answers https://github.com/NGnius/PowerTools/wiki/FAQ
