### ISSUE TITLE
Profiles not applying

### ISSUE THREAD

**Issue by Mudgie0205** [NGnius/PowerTools#45]
Profiles don’t apply when loading a game but do once changing PowerTools settings after launch. After quitting and launching again, the profile still doesn’t apply. Persistent is enabled

**Comment by Mudgie0205** [comment]
Turns out you can’t have Steam game profiles enabled at the same time if you use any of the power settings

**Comment by NGnius** [comment]
You can have Steam game profiles enabled, but it's best to not set the settings in the vanilla power settings as well as in PowerTools since they'll fight.

I purposefully set it so that vanilla Steam wins in most cases, with the exception of setting them through PowerTools. On resume/restart, vanilla settings should be applied.

**Comment by Mudgie0205** [comment]
> On resume/restart, vanilla settings should be applied.

Thanks for replying. Do you mean vanilla settings are applied when both steam profiles and PowerTools profiles are enabled? I ask because if I only have PowerTools profiles enabled, the settings apply even if I restart the app, device, or wake from suspend (which is unfortunate if you use 60Hz and 40Hz for different games as you have to manually ensure the desires refresh rate is set per game to keep PowerTools active with the intended refresh rate.

**Comment by NGnius** [comment]
I mean don't set, for e.g. GPU clock speeds in the vanilla settings as well as in PowerTools. Unrelated settings shouldn't fight.

**Comment by Mudgie0205** [comment]
I take it unrelated settings are ones are those which they both don’t share such as PPT, Threads, and underclock RAM (although that doesn’t appear to work upon restart) what does persistent actually do then if it doesn’t apply through resume, device or app/game restart?

I can keep GPU and clock and CPU W set  with a Steam Deck profile in Dark Souls  PTDE and refresh rate at 60/frame rate at 30 but SpongeBob Bikini Bottom increases them. It’s rather confusing and I don’t understand why. I’ll continue to investigate and open a new case if I discover anomalies

**Comment by NGnius** [comment]
Fast & Slow PPT conflict with TDP settings, GPU min & max conflict with manual GPU clock control
