### ISSUE TITLE
Lower minimum CPU frequency

### ISSUE THREAD

**Issue by Mudgie0205** [NGnius/PowerTools#46]
Would be useful for power saving reasons to be able to set minimum CPU frequency to 500MHz

**Comment by NGnius** [comment]
This is a hardware limitation. I'm only exposing the range of values accepted by the kernel.

**Comment by Mudgie0205** [comment]
There’s no way of altering the Linux kernel manually to change this user-side?

**Comment by NGnius** [comment]
Not without firmware or kernel modifications, which are outside the scope of PowerTools.

**Comment by Mudgie0205** [comment]
Yeah my edits don’t even apply in the cpupower.txt file under ~/etc/default/ folder. I guess it’s much more involved than that. (Sorry to sound like such a noob pleb. It’s my first delve into Linux for nearly 10 years and was never super versed on it even then)
