### ISSUE TITLE
Add game profiles to power tools

### ISSUE THREAD

**Issue by L0WR1D3Rz** [NGnius/PowerTools#47]
Is it possible to add a game profile toggle to power tools so that it remembers automatically the settings according to the game/app launched, similar to how the performance tab or vibrantdeck plugin work? This would be a great quality of life improvement which will help users "set it and forget it" and not have to readjust sliders each time the steam deck reboots or each time a different game is launched.

**Comment by NGnius** [comment]
Have you tried enabling persistence? Because this functionality is already there, just off by default (like Valve does).
