### ISSUE TITLE
Plugin seems to be in a read only behavior

### ISSUE THREAD

**Issue by chrisgix** [NGnius/PowerTools#5]
**Expected Behaviour**
I am able to open the plugin and modify values

**Actual Behaviour**
The plugin is not rendering and is in a read only state

**To Reproduce**
1. Press '...'
2. Click on the plugin icon
3. Click power tools

**Screenshots**
![PXL_20220512_001605791](https://user-images.githubusercontent.com/15004447/167967553-1571586e-5037-41dc-b8a3-3d2276ff202c.jpg)

**Comment by NGnius** [comment]
Looks like the update to SteamOS today broke some stuff. I'll look into it

**Comment by donannis** [comment]
Was just about to come in and say this. looks like the update broke it.

**Comment by johnlietzke** [comment]
Yes, also just noticed this after updating.

**Comment by NGnius** [comment]
This should be solved in v0.4.1

**Comment by johnlietzke** [comment]
Thanks.  

Just waiting for you to update the PlugInLoader page to install and test.  I am lazy, I know.
