### ISSUE TITLE
GPU overrides not auto applying

### ISSUE THREAD

**Issue by AndehX** [NGnius/PowerTools#64]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I am doing something good

### Expected Behaviour

Any manually set frequency limits should apply automatically when starting a game up.

### Actual Behaviour

Frequency limits don't seem to apply until you open power tools and move one of the frequency sliders (max or min) one notch, then the frequency suddenly jumps to whatever you manually set it to.

It's worth noting that this issue doesn't always appear to happen.  Happens to me maybe 40% of the time.

### Steps To Reproduce

I was testing this in Cemu emulator.
Simply manually set GPU frequency, (i set it to max for testing) then restart the game.
GPU frequency stays around 1000, until you go into power tools and "refresh" your frequency setting.

### Version

1.1.0 (Indev)

### Version

Steam Deck

**Comment by NGnius** [comment]
This should be fixed in [8332649](https://github.com/NGnius/PowerTools/commit/8332649e45f43c7df8db2336554db4cfdae8ff63), which is also packaged as `v1.1.0-beta2`
