### ISSUE TITLE
Error while selecting tdp limit in powertools

### ISSUE THREAD

**Issue by cloudsteamff** [NGnius/PowerTools#66]
### Please confirm

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] I will fill this out to the best of my ability

### Expected Behaviour

I'm using holoiso maybe it's because it blocks tdp changing but i'm on steamdeck so i don't know for sure. Is there a way to reenable tdp changing? 

### Actual Behaviour

It says something went wrong while displaying this content
Error reference: Shared SteamUI_7744155_ceda898a4d875afa
e.toFixed is not a function

### Steps To Reproduce

Open powertools try to change tdp under cpu settings 
![IMG_20230121_160842](https://user-images.githubusercontent.com/123211020/213873174-58242fd1-ae4b-4e8b-b7b0-ecd41992b4bb.jpg)

### Version

1.0.5 (Latest stable)

### Platform

Steam Deck

### OS

Holoiso

**Comment by NGnius** [comment]
Please fill out the first section, otherwise it's not worth anyone's time to help you.

You also mention TDP, while PowerTools v1.0 doesn't have a TDP slider. Did you mean slow PPT or fast PPT per chance?

**Comment by cloudsteamff** [comment]
Clicking on powerplay limits override apu tdp settings

Il sab 21 gen 2023, 16:56 NGnius (Graham) ***@***.***> ha
scritto:

**Comment by cloudsteamff** [comment]
Clicking on powerplay limits override apu tdp settings

**Comment by NGnius** [comment]
Closing as stale
