### ISSUE TITLE
Where should I put pt_oc.json?

### ISSUE THREAD

**Issue by mio-19** [NGnius/PowerTools#69]
### Please confirm

- [ ] I have searched existing issues
- [ ] This issue is not a duplicate of an existing one
- [ ] I will fill this out to the best of my ability

### Describe what you'd like to be able to do

I set max cpu clock to 3900 and put modified pt_oc.json at both homebrew/plugins/PowerTools and homebrew/settings/PowerTools. After restarting plugin_loader service, the max cpu limit is still 3500

### Describe alternatives you've considered

N/A

**Comment by NGnius** [comment]
Please read the wiki https://github.com/NGnius/PowerTools/wiki/Customization#steam-deck
