### ISSUE TITLE
Custom Slider: PowerTools stop working if Max CPU frequency is set beyond 3.5GHz

### ISSUE THREAD

**Issue by maximilian101** [NGnius/PowerTools#74]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

Set both Min and Max CPU frequency at 4GHz with the new custom slider.

### Actual Behaviour

PowertTools stop working if Max CPU frequency is set beyond 3.5GHz. If the Max CPU frequency is set at 3.6GHz, the slider for all other settings in PowerTools will stop working and default to last known setting. If the Max CPU frequency fall back to 3.5GHz, PowerTools will start working again.

### Steps To Reproduce

{
    "battery": {
        "charge_rate": {"min": 250, "max": 2500}
    },
    "cpus": {
        "cpus": [
            {
                "clock_min": {"min": 400, "max": 4000},
                "clock_max": {"min": 400, "max": 4000},
                "clock_step": 100
            },
            {
                "clock_min": {"min": 400, "max": 4000},
                "clock_max": {"min": 400, "max": 4000},
                "clock_step": 100
            },
            {
                "clock_min": {"min": 400, "max": 4000},
                "clock_max": {"min": 400, "max": 4000},
                "clock_step": 100
            },
            {
                "clock_min": {"min": 400, "max": 4000},
                "clock_max": {"min": 400, "max": 4000},
                "clock_step": 100
            },
            {
                "clock_min": {"min": 400, "max": 4000},
                "clock_max": {"min": 400, "max": 4000},
                "clock_step": 100
            },
            {
                "clock_min": {"min": 400, "max": 4000},
                "clock_max": {"min": 400, "max": 4000},
                "clock_step": 100
            },
            {
                "clock_min": {"min": 400, "max": 4000},
                "clock_max": {"min": 400, "max": 4000},
                "clock_step": 100
            },
            {
                "clock_min": {"min": 400, "max": 4000},
                "clock_max": {"min": 400, "max": 4000},
                "clock_step": 100
            }
        ],
        "global_governors": false
    },
    "gpu": {
        "fast_ppt": {"min": 1000000, "max": 30000000},
        "slow_ppt": {"min": 1000000, "max": 29000000},
        "ppt_divisor": 1000000,
        "ppt_step": 1,
        "clock_min": {"min": 200, "max": 2000},
        "clock_max": {"min": 200, "max": 2000},
        "clock_step": 100
    }
}

### Anything else?

18:09:18 [INFO] Steam Deck limits file /home/deck/.config/powertools/pt_oc.json found
18:09:18 [INFO] Steam Deck limits file /home/deck/.config/powertools/pt_oc.json found
18:09:18 [INFO] Steam Deck limits file /home/deck/.config/powertools/pt_oc.json found
18:09:18 [INFO] Loaded settings with drivers general:AutoDetect,cpus:SteamDeckAdvance,gpu:SteamDeckAdvance,battery:SteamDeckAdvance
18:09:18 [INFO] Loaded main settings file? true
18:09:18 [INFO] FRONT-END: POWERTOOLS: Governors from backend schedutil,schedutil,schedutil,schedutil,schedutil,schedutil,schedutil,schedutil
18:09:20 [INFO] Loaded settings file? false
18:09:20 [INFO] FRONT-END: POWERTOOLS: Governors from backend schedutil,schedutil,schedutil,schedutil,schedutil,schedutil,schedutil,schedutil
18:17:05 [WARN] read_current_now err: Failed to read from `/sys/class/power_supply/BAT1/current_now`: io: No such device (os error 19)
18:17:05 [WARN] FRONT-END: A resolve failed
18:17:12 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3900
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:12 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3900
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:12 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3900
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:12 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3900
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3800
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3800
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3800
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3800
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3700
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3700
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3700
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3700
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3600
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3600
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3600
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 0 1 3600
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 1 1 3600
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:13 [ERROR] Settings on_set() err: CPU setting error: Failed to write `p 2 1 3600
` to `/sys/class/drm/card0/device/pp_od_clk_voltage`: Invalid argument (os error 22)
18:17:16 [WARN] read_current_now err: Failed to read from `/sys/class/power_supply/BAT1/current_now`: io: No such device (os error 19)
18:17:18 [ERROR] Got USDPL call with strange ID! got:45323 last id:45247 (rejecting packet)
[powertools-rs.log](https://github.com/NGnius/PowerTools/files/10773442/powertools-rs.log)

### Version

1.1.0 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Stable)

**Comment by NGnius** [comment]
> NOTE: since some kernel interfaces only accept the default Steam Deck ranges, changing certain ranges is only a placebo in the UI. The log is your friend to find out when this is happening.

https://github.com/NGnius/PowerTools/wiki/Customization#steam-deck
