### ISSUE TITLE
GPU stuck at 200Mhz after Rebooting Steam Deck

### ISSUE THREAD

**Issue by tobio225** [NGnius/PowerTools#76]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

GPU Clock not being stuck after Reboot.

### Actual Behaviour

GPU Clock is stuck at 200 Mhz after Reboot. After changing the clock speed manually either in Deck overlay or Powertools Plugin, the GPU is behaving normally again. 

### Steps To Reproduce

1. Install Powertools Plugin
2. Tinker with GPU Clock Speed
3. Turn the altered GPU Clocks off again (so that the Clockspeed is variable again)
4. Reboot Steam Deck
5. GPU Clock is stuck at 200Mhz (CPU is still behaving normally)

### Version

1.1.0 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Stable)

**Comment by NGnius** [comment]
I took a look at this with the performance overlay enabled in the menu, and I noticed something slightly different from what you're describing: the GPU will boost above 200MHz, but under light to moderate loads it doesn't. Seems like the boost behaviour is just very conservative at the minimum.

Can you confirm this is what's happening for you too? It may take a bit of work to get the GPU under enough load to boost above 200MHz (I found that selecting an item in the News section of Home, then waiting a second and watching the GPU clock worked).

**Comment by tobio225** [comment]
For me launching and trying to play a game (Dirt Rally 2.0) didn't even force the GPU to go higher than 200Mhz. With these 200Mhz the GPU was at 100% load in game and the game stuttered. Only thing that helped was manually adjusting the GPU clock. I can try to go to the News menu and see what happens tomorrow and report.

**Comment by NGnius** [comment]
Ok I'm definitely not seeing that. I launched Stray to check and it got the GPU to boost higher as well.

Can you upload your logs and, if persistent, the PowerTools config for the games that are having the issue?

**Comment by tobio225** [comment]
Sure, i will get back to you tomorrow. Where do i find the log and profile files?

**Comment by NGnius** [comment]
the log file `/tmp/powertools-rs.log`
the config files are in `~/.config/powertools` (each `<ID>.json` corresponds to the game ID used by Steam)

**Comment by tobio225** [comment]
OK, so here are the log files. I don't have a powertools-folder in .config, so i cannot find the config files...

[after_reboot_powertools-rs.log](https://github.com/NGnius/PowerTools/files/10790400/after_reboot_powertools-rs.log)
[before_reboot_powertools-rs.log](https://github.com/NGnius/PowerTools/files/10790401/before_reboot_powertools-rs.log)

Here's what i did:

1. File "before reboot":
- Install Powertools plugin from decky (was uninstalled from the day before to confirm the stuck GPU resulted from the plugin)
- tried to open it, got an error screen with the message to hit refresh
- hit refresh --> decky was gone from the (...)-menu
- reboot steam deck
- decky was back, powertools plugin could be opened (despite the reboot GPU clock was behaving)
- start Dirt Rally 2.0
- adjusted GPU max. clock for testing
- setting GPU max. Clock back to default 1600Mhz
- close game
- safe the log file
- reboot steam deck

2. File "after reboot":
- Deck rebooted --> GPU Clock was stuck at 200Mhz in Steam
- hovering around the menus, trying to push load on the GPU did not boost the clock (~75% load)
- start Dirt Rally 2.0
- GPU Clock still stuck at 200Mhz
- Open Powertools plugin and adjust min. GPU Clock to 300Mhz
- GPU started boosting like normal immediately
- close game
- safe log file.

Rebooting afterwards gave me back the stuck GPU at 200Mhz. Uninstalling the powertools plugin and rebooting again fixed it.

**Comment by NGnius** [comment]
If you set the minimum GPU clock to 300 or 400MHz permanently, does the GPU still refuse to boost after a reboot?

**Comment by tobio225** [comment]
No, that didnt work either. After setting min. Clock to 300mhz and rebooting, the GPU is still stuck AT 200Mhz. Also the decky loader disappeared completely from the (...)-menu after the reboot. Another reboot brought decky back, the gpu stuck at 200mhz and the setting of 300mhz Was not saved in the powertools plugin....

**Comment by NGnius** [comment]
Did you also set the persistent profile toggle?

**Comment by tobio225** [comment]
nope, i hadn't. Seems to work now with that switch on. Even seems to work with GPU clock set to 200Mhz.... Did a couple of reboots and it seems fine.

As soon as i toggle that switch off again, the GPU is stuck at 200Mhz after next reboot... 

I also tested the behaviour with the toggle for GPU frequency limit --> if toggled on (and persistent profile toggled on) there seems to be no problem. If toggled of (no matter if persistent profile is on or off) --> GPU stuck again at 200Mhz.
