### ISSUE TITLE
After last decky and steam update plugin page is not available

### ISSUE THREAD

**Issue by phush0** [NGnius/PowerTools#77]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

It should display normal page

### Actual Behaviour

It display only placeholder
![15B63301-BE8C-4E0A-A7E1-C9E10E8CC834_1_102_o](https://user-images.githubusercontent.com/5719362/221117253-282403aa-bf60-4608-a35b-6e7353ed2eac.jpeg)

### Steps To Reproduce

1. Latest Steam Beta
2. Latest Decky Preview
3. go to PowerTools tab
4. profit

### Version

1.1.0 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Preview/Beta)

**Comment by phush0** [comment]
I have to say it is same for all plugins. Fantastic is with same problem

**Comment by NGnius** [comment]
Yeah known issue. Please use SteamOS Stable.
