### ISSUE TITLE
Powertools empty when launching yuzu

### ISSUE THREAD

**Issue by james2432** [NGnius/PowerTools#83]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

Being able to configure stuff

### Actual Behaviour

![PXL_20230319_210008669](https://user-images.githubusercontent.com/498547/226208796-2b2ef27e-cce8-4b2c-a389-8fafa450f84d.jpg)

### Steps To Reproduce

1. Launch yuzu with rom
2. Open Powertools

### Version

1.2.0 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Preview/Beta)

**Comment by NGnius** [comment]
This is probably the Decky bug which causes blank plugins

**Comment by mikehgentry** [comment]
FWIW I'm seeing this too, and it's been reported on Decky's bug tracker https://github.com/SteamDeckHomebrew/decky-loader/issues/383 (I think they closed that in error, mistaking it for another bug?)

I've found if it happens exiting Decky with the the 'b' button then reentering Powertools again works.

**Comment by NGnius** [comment]
The issue you linked is about an old UI bug caused by an update to SteamOS which required every plugin to be updated (PowerTools included; completed in v1.3.0 iirc)

**Comment by NullScope** [comment]
Hi @NGnius I'm still facing this issue even on v1.3.1-1 and Decky 2.7.0, albeit its doing it randomly while playing some games (I sometimes open the tab to check for the charging status) and it can be "solved" by opening the decky settings and going back to the PowerTools tab again. This doesn't happen with other plugins except the Bluetooth one.

Should I submit the decky logs here?

**Comment by NGnius** [comment]
You'd be better off submitting them to Decky loader. This isn't a PowerTools bug so sending me reports about it won't change anything.
