### ISSUE TITLE
Not reapplying settings saved in profile

### ISSUE THREAD

**Issue by Lyzing** [NGnius/PowerTools#85]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

I saved a profile with a custon TDP and CPU Clock, when I start the game next time I expect these settings to be loaded and applied automatically.

### Actual Behaviour

The settings are correctly loaded at the PowerTools UI of Decky but the CPU clocks are not applied, and probably also not the other settings (not sure about that), Sometimes I have to slide each slider back and forth once to get it to actually apply the settings other times it's enough to open the PowerTools UI to make it apply the settings.

### Steps To Reproduce

1. Start a Game
2. Adjust some settings in PowerTools UI on Decky
3. Check "Save Persistent Profile"
4. Restart the Game with Overlay visible where we see the CPU Clocks

### Anything else?

I think what happens here is that sometimes PowerTools applies the settings before Steam applies it's game profile settings and because of that the PowerTool changes get overwritten and not reapplied automatically, so maybe a check that checks every x seconds if the settings are applied could solve it?

### Version

1.2.0 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Stable)

**Comment by NGnius** [comment]
Did you create a pt_oc.json file with custom CPU ranges?

Otherwise, can you send your log after doing the reproduction steps? The log is at `/tmp/powertools.log` but resets when your reboot your machine.

**Comment by Lyzing** [comment]
Yes I had a "pt_oc.json" file, it was not out of range but the syntax of the file looked outdated so I recreated the file with the new syntax, everything works as expected now, thank you.

**Comment by NGnius** [comment]
It might have been using an older version with the wrong limits (a bug from v1.1.0 iirc). If you're not changing anything, leaving pt_oc.json around isn't really worth it.
