### ISSUE TITLE
Persistent Profile doesn't work for Non Steam games after SteamDeck update 

### ISSUE THREAD

**Issue by dPandl** [NGnius/PowerTools#86]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

If I start for example Mario Kart 8 the Profile in Powertools should switch to Mario Kart 8 and apply/remember my configs. If i close Mario Kart 8 the Profile should go back to Main.

### Actual Behaviour

When I start for example Mario Kart 8 the Profile in Powertools does stay on Main. It won't apply/remember any of my configs.

### Steps To Reproduce

1. Open non steam game
2. Open Powertools
3. Look for Profile

### Version

1.2.0 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Stable)

**Comment by NGnius** [comment]
I can't reproduce this, but I found a related bug while trying to repro it (sometimes the Main profiles gets the wrong name). Can you restart your Deck and try again? The hooks into the steam client may have gotten lost.

**Comment by dPandl** [comment]
I restart it several times. I even uninstalled powertools and reinstalled it. And i downgraded powertools and updated again, nothing does fix it. All the steam games work well tho. I also checked if it may be the case that just the Profile Name wouldn't change. But if i am playing a game, do my settings and close it, settings like smt stay like i set it in the game. I don't know what to do. But i need to say that since the last steam update i have several issues regarding the steamdeck as a whole and also with other decky plugins. VibrantDeck on the other hand recognizes every non steam game.

**Comment by NGnius** [comment]
Huh strange. Can you upload your log with this happening? `/tmp/powertools.log` (the logs is cleared when the machine reboots)

**Comment by dPandl** [comment]
[powertools.log](https://github.com/NGnius/PowerTools/files/11066010/powertools.log)

**Comment by NGnius** [comment]
The logs show a persistent main profile being loaded, then a game's persistent profile getting loaded, and then the main profile being loaded again. Is it possible your Mario Kart profile has the same name as the main profile? The UI won't update if the profile name doesn't change, regardless of whether the actual settings are different

**Comment by dPandl** [comment]
The log was created like this:
I restarted my Deck, i launched Mario Kart, i played a while, then closed it. I then launched just cause 3 and closed it. Then i went to desktop mode and sent the log.

No none steam game works for me with persistent settings in Powertools, it shows "Main" for every non steam game. How can i change profile names? I would like to try that to solve the issue. 

Is there maybe a way to completely reset powertools without resetting my SteamDeck? As i had written, i had uninstalled, and downgraded and updated powertools, but it didn't help.

**Comment by NGnius** [comment]
That would explain the long time between the initial startup and the main profile getting (re)loaded. The log doesn't show any profile loading activities at all when you were playing Mario Kart, so that must mean it's an issue with the fronted. Unfortunately it's hard to get those logs.

Unfortunately I'm no closer to reproducing it. I've been testing with Firefox and it all seems to work without issue. How old are your non-steam games (and/or your Steam Deck)?

You can delete all of the PowerTools config files under `~/.config/powertools` to reset PowerTools. Might be a good idea to reboot your Deck right after.

**Comment by dPandl** [comment]
I just found out that not even the decks own performance profiles for non steam games work, i think i just need to factory reset my unit :/ . I did not think of that before because i am not using it normally. I'm really sorry

**Comment by dPandl** [comment]
So i found the issue as i didn't want ro reset my SteamDeck. Turns out that the issue had nothing to do with powertools, it came from MetaDeck. I just uninstalled it and restartet Steam. Now everything works well again. I am very grateful that you took the time to address my problem and I am very sorry if I wasted your time.
