### ISSUE TITLE
Power tools 1.3 continuously updates default_settings.json

### ISSUE THREAD

**Issue by alexandru-stefan-miron** [NGnius/PowerTools#90]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

Config files should be written on an as needed basis.

### Actual Behaviour

Default_settings.json is written continuously for no apparent reason.

### Steps To Reproduce

Go to ~/.config/powertools and check the timestamp of default_settings.json that is updated.

### Version

1.3.0 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Preview/Beta)

**Comment by NGnius** [comment]
This is fixed in v1.3.1
