### ISSUE TITLE
"Persistent Profile" Loads "[Charge] Maximum" as [Value] * 100

### ISSUE THREAD

**Issue by rigbyrj** [NGnius/PowerTools#91]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

Expected behaviour is to...

- Set "**Charge Limit**" to **On/Enabled**, then...
- Set "**[Charge] Maximum (%)**" to (for example) "**70**", then...
- Charge is limited to 70% as expected.
- Set "**Persistent Profile**" to **On/Enabled**, then...
- Reboot Steam Deck, view the Power Tools menu, and "[Charge] Maximum (%)" should read "70", and system charge should still be **limited** to 70%.

### Actual Behaviour

Actual behaviour is...

- Set "**Charge Limit**" to **On/Enabled**, then...
- Set "**[Charge] Maximum (%)**" to (for example) "**70**", then...
- Charge is limited to 70%, as expected.
- Set "**Persistent Profile**" to **On/Enabled**, then...
- Reboot Steam Deck, view the Power Tools menu, and "[Charge] Maximum (%)" reads "7000", and system charge is **not limited** to 70%.
- Edit the "[Charge] Maximum (%)" Slider from "7000" to "70", and then charge is limited again.

### Steps To Reproduce

Please see details steps above in Expected/Actual Behaviour.

### Anything else?

Also, would it be possible to make the charge limit apply system-wide please, rather than be a different setting per game? I think most users would prefer to have one charge limit applied everywhere, rather than have to apply the charge limit to every new game they start.

### Version

1.3.0 (Latest stable)

### Platform

Steam Deck

### OS

SteamOS 3 (Stable)

**Comment by NGnius** [comment]
This is fixed in v1.3.1

**Comment by rigbyrj** [comment]
> This is fixed in v1.3.1

Thank you 😊
