### ISSUE TITLE
Decky latest version is still 1.3.0

### ISSUE THREAD

**Issue by Viexi** [NGnius/PowerTools#93]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

Decky update should presumably update to 1.3.1

### Actual Behaviour

v1.3.1 is not able to be updated to on the release channel of Decky Loader

### Steps To Reproduce

1. Open Decky Loader
2. Ensure update channel for plugins is "release"
3. Go to plugins screen
4. Latest version is 1.3.0 or, if already updated, no update is available

### Anything else?

1.3.1 is available when using the preview channel.

### Version

Alpha/Beta/RC version

### Platform

Steam Deck

### OS

SteamOS 3 (Stable)

**Comment by NGnius** [comment]
> 1.3.1 is available when using the preview channel.

I presume you mean the testing store.

This is a feature of the Decky store, it requires a code review and manual testing before any plugin can be added/updated on the default store. I'm not allowed to test my own plugin, so I'm waiting for anyone else to do it.

**Comment by Viexi** [comment]
> > 1.3.1 is available when using the preview channel.
> 
> I presume you mean the testing store.
> 
> This is a feature of the Decky store, it requires a code review and manual testing before any plugin can be added/updated on the default store. I'm not allowed to test my own plugin, so I'm waiting for anyone else to do it.

Yes sorry that is correct - thank you for the information! That makes a lot of sense and I don’t think that’s policy is very obvious to most end users like myself.

Thanks again 😊
