### ISSUE TITLE
CPU frequency limiter locks frequency for some cores to 3000-3100mhz until restart

### ISSUE THREAD

**Issue by claytankozmo** [NGnius/PowerTools#97]
### Please confirm

- [X] I have searched existing issues
- [X] This issue is not a duplicate of an existing one
- [X] I will fill this out to the best of my ability

### Expected Behaviour

I have installed a pt_oc.json file, and I changed all the values to 3900.  Locking to 3900 for minimum and maximum should get me 3900mhz locked, especially with SMT disabled.

### Actual Behaviour

It locks 2-3 cores (was different each time) to 3900mhz, and the other 1-2 cores to 3000mhz.  This persists despite toggling SMT off or on, reapply settings, frequency off.   Those cores are just forever locked to 3000mhz until I restart my deck.

### Steps To Reproduce

Set CPU minimum and max to 3500 (assuming its the same for non-oc deck) and some cores will be stuck at 3000mhz.

### Version

Alpha/Beta/RC version

### Platform

Steam Deck

### OS

SteamOS 3 (Preview/Beta)

**Comment by NGnius** [comment]
Have you checked what the logs say?

**Comment by NGnius** [comment]
Closing since I haven't received a response in over a month
